keys:
  - &tne age16ugadfgq0g5qvezf7jlp3tyf400msle9k40wn5vtundd4jw2wd8qvuw23g
  - &nico age1hvfhax6eysywun0up8um52yj435z99xq3wpu2py54je263hmjfqsjguk0z
  - &stormwing age1fesput9yl8q0kvhejrjxaesxp2z9208pnex7gghjahmn0xemcuvqlrg92t
  - &aerialis age1cjuy5mc4fphcc3x4x9uh6puzhetrsuzaa4kn9j3edjvfa0rrcfasjchnkk
  - &nico-yubikey D245D484F3578CB17FD6DA6B67DB29BFF3C96757
creation_rules:
  - path_regex: secrets/shared.yaml$
    key_groups:
      - age:
          - *tne
          - *nico
          - *stormwing
          - *aerialis
        pgp:
          - *nico-yubikey
