---
- hosts: nix
  gather_facts: no
  become: true
  tasks:
    - name: Update nix flake and push to cachix
      shell: nix flake update && export CACHIX_AUTH_TOKEN="$(<"/var/garuda/secrets/cachix")" && nix flake archive --json | jq -r '.inputs|to_entries[].value.path' | cachix push garuda-linux && nix-store -qR --include-outputs $(nix-store -qd $(nix build '.#nixosConfigurations."cachix".config.cachix' --json  | jq -r '.[].outputs | to_entries[].value')) | grep -v '\.drv$' | cachix push garuda-linux
      args:
        chdir: /etc/nixos
      run_once: true
    - name: Download flake lock to repo
      fetch:
        src: "/etc/nixos/flake.lock"
        dest: "nix/flake.lock"
        flat: true
      run_once: true
    - name: Upload flake lock to hosts
      synchronize:
        src: "nix/flake.lock"
        dest: "/etc/nixos/flake.lock"
    - name: Update and build system
      shell: nixos-rebuild boot
