// @ts-check
/// <reference path="types-dnscontrol.d.ts" />
var REG_NONE = NewRegistrar("none");
var DNS_CLOUDFLAREAPI = NewDnsProvider("cloudflare");

D("garudalinux.com", REG_NONE, DnsProvider(DNS_CLOUDFLAREAPI),
    DefaultTTL(1),
    ALIAS("@", "garudalinux.org.", CF_PROXY_ON),
    TXT("@", "v=spf1 -all"),
    CNAME("www", "garudalinux.org.", CF_PROXY_ON),
);

D("garudalinux.net", REG_NONE, DnsProvider(DNS_CLOUDFLAREAPI),
    DefaultTTL(1),
    ALIAS("@", "garudalinux.org.", CF_PROXY_ON),
    TXT("@", "v=spf1 -all"),
    CNAME("alertmanager", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("docs", "infrastructure-nix.pages.dev.", CF_PROXY_ON),
    CNAME("grafana", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("loki", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    A("mail", "157.180.57.100"),
    CNAME("n8n", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("n8n-webhooks", "mail.garudalinux.net.", CF_PROXY_ON),
    CNAME("pgadmin", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("prometheus", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("syncthing-build", "951d97c6-d3fa-4f64-a7a0-fdcd748a962d.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("www", "garudalinux.org.", CF_PROXY_ON),
);

D("garudalinux.org", REG_NONE, CF_MANAGE_COMMENTS, DnsProvider(DNS_CLOUDFLAREAPI),
    DefaultTTL(1),
    ALIAS("@", "aerialis.garudalinux.org.", CF_PROXY_ON),
    MX("@", 10, "mail.garudalinux.net."),
    TXT("@", "google-site-verification=n3-Dy92v5aRQc84etxD4noIdAflWRt6ADDFEyEM0pf8"),
    TXT("@", "https://keyoxide.org/D245D484F3578CB17FD6DA6B67DB29BFF3C96757"),
    TXT("@", "keybase-site-verification=AosG5PEJlzwY6ec6glKrIroeA9HuJagRTRRMHrCJqpc"),
    TXT("@", "v=spf1 mx a -all"),
    TXT("_atproto", "did=did:plc:vkmmzruserxsz74d5fp6ab3u", CF_COMMENT("Bluesky verification for @garudalinux.org")),
    TXT("_dmarc", "v=DMARC1;  p=none; rua=mailto:a30ca0d65efb4cae8fdc80e3934371c2@dmarc-reports.cloudflare.net"),
    TXT("mail._domainkey", "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDiUCPvD13QrzyPKlRKfZD01s8KOC5uSYjoRTahrJPNvmTd8MXe1rrN9hMFaZnSA/XJlEQqfbzYjgKSn2dAhv22dH/+5lHtYOINaahRAB9sITaxI9RqrwW7dkEDY4rrX9QDBml/NwH0PC7Qtnyg+zDmJ/GSnU1y1hSWQE76f/o7zwIDAQAB"),
    A("aerialis", "157.180.57.100"),
    CNAME("bin", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("bitwarden", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("builds", "stormwing.garudalinux.org."),
    CNAME("iso.builds", "stormwing.garudalinux.org."),
    CNAME("cf-builds", "builds.garudalinux.org."),
    A("ch-mirror", "140.238.219.13"),
    CNAME("chaotic-backend", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("cloud-aio", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("cloud-temp", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("db", "aerialis.garudalinux.org."),
    CNAME("ffsync", "aerialis.garudalinux.org."),
    CNAME("firedragon", "documentation-b9l.pages.dev.", CF_PROXY_ON),
    CNAME("forum", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("librey", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("lingva", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("mail", "aerialis.garudalinux.org."),
    CNAME("nix", "garuda-nix-subsystem.pages.dev.", CF_PROXY_ON),
    CNAME("search", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("searx", "00995e3f-e264-455f-bf49-a4eacbf48e9a.cfargotunnel.com.", CF_PROXY_ON),
    CNAME("social", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("social-video", "social.garudalinux.org."),
    CNAME("start", "aerialis.garudalinux.org.", CF_PROXY_ON),
    A("status", "5.45.102.71", CF_PROXY_ON),
    AAAA("status", "2a03:4000:6:eef:1436:a6ff:fed3:92ba", CF_PROXY_ON),
    A("stormwing", "157.180.57.51"),
    TXT("_atproto.tne", "did=did:plc:sqtxwvdumkbyt7uo377ooolp", CF_COMMENT("Bluesky verification for @tne.garudalinux.org")),
    CNAME("vault", "aerialis.garudalinux.org."),
    CNAME("wiki", "aerialis.garudalinux.org.", CF_PROXY_ON),
    CNAME("www", "aerialis.garudalinux.org.", CF_PROXY_ON),
);
