- name: Apply NixOS configuration
  hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Build system
      ansible.builtin.command: nixos-rebuild switch -j7
      changed_when: false
