- name: Deploy NixOS configurations
  hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Deploy Nix files
      ansible.posix.synchronize:
        dest: /etc/nixos/
        archive: true
        src: ../../../
        delete: true
        rsync_opts:
          - "--delete-excluded"
