- name: Update flake.lock and apply changes
  hosts: nix
  gather_facts: false
  become: true
  tasks:
    - name: Update nix flake
      ansible.builtin.shell: nix flake update
      args:
        chdir: /etc/nixos
      changed_when: false
      run_once: true
    - name: Download flake lock to repo
      ansible.builtin.fetch:
        dest: ../../flake.lock
        flat: true
        src: /etc/nixos/flake.lock
      run_once: true
    - name: Upload flake lock to hosts
      ansible.posix.synchronize:
        dest: /etc/nixos/flake.lock
        src: ../../flake.lock
    - name: Update and build system
      ansible.builtin.shell: systemctl restart nix-daemon && nixos-rebuild boot -j7
      changed_when: false
