---
version: "3.9"
services:
  github-runner:
    image: myoung34/github-runner:2.309.0
    container_name: github-runner
    privileged: true
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN:-?err}
      EPHEMERAL: true
      LABELS: nyxbuilder
      ORG_NAME: chaotic-cx
      RUNNER_NAME: immortalis
      RUNNER_SCOPE: org
      RUNNER_WORKDIR: /tmp/runner/work
    volumes: [/tmp/runner:/tmp/runner]
    restart: never
