[book]
authors = ["dr460nf1r3", "TNE"]
description = "Contains the documentation for the Garuda Linux infrastructure."
language = "en"
src = "src"
title = "Garuda's infra documentation"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "mocha"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/garuda-linux/infrastructure-nix"
site-url = "https://docs.garudalinux.net"
