services:
  chaotic-backend:
    image: ghcr.io/chaotic-cx/chaotic-next:1.12.0
    container_name: chaotic-backend
    deploy:
      restart_policy:
        condition: always
        delay: 30s
    environment:
      AUR_USERNAME: ${AUR_USERNAME:-?err}
      AUR_PASSWORD: ${AUR_PASSWORD:-?err}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-?err}
      BETTER_AUTH_TRUSTED_ORIGINS: https://aur.chaotic.cx
      BETTER_AUTH_URL: https://aur.chaotic.cx/backend
      CAUR_DB_KEY: ${CAUR_DB_KEY:-?err}
      CAUR_GITLAB_TOKEN: ${TEMERAIRE_BOT_TOKEN:-?err}
      CAUR_GITLAB_WEBHOOK_TOKEN: ${CAUR_GITLAB_WEBHOOK_TOKEN:-?err}
      CAUR_MANAGER_API_TOKEN: ${CAUR_MANAGER_API_TOKEN:-?err}
      CAUR_TRUST_PROXY: 172.18.0.1
      CAUR_VAPID_PRIVATE: ${CAUR_VAPID_PRIVATE:-?err}
      CAUR_VAPID_PUBLIC: BFMijCyTcLZu3HRJyMfoB4vtnDcgl7E2SVZgd4uWB3XjO2VvRh_LjYHcY_oJLvMIhdp5Yvuz0gudRpY-PFI9iWA
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID:-?err}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET:-?err}
      GITLAB_REDIRECT_URI: https://aur.chaotic.cx/backend/api/auth/oauth2/callback/gitlab
      LOG_LEVEL: debug
      NODE_ENV: production
      PG_DATABASE: chaotic-aur
      PG_HOST: 10.0.5.20
      PG_PASSWORD: ${PG_PASSWORD:-?err}
      PG_USER: chaotic-aur
      REDIS_PASSWORD: ${REDIS_PASSWORD:-?err}
      REDIS_SSH_HOST: host.docker.internal
      REDIS_SSH_USER: package-deployer
      REPOMANAGER_ABI_DRY_RUN: false
      REPOMANAGER_MIRROR_URL: https://builds.garudalinux.org/arch-mirror
      REPOMANAGER_SIGNAL_SCAN_ENABLED: true
      VIRUSTOTAL_API_KEY: ${VIRUSTOTAL_API_KEY:-?err}
    ports: ["3000:3000"]
    volumes: ["${SSH_KEY:-?err}:/app/sshkey", "./backend-config:/app/config"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  # TODO: revert to NixOS service once it no longer segfaults
  database:
    image: redis:8.2-m01-alpine
    container_name: chaotic-database
    restart: always
    ports: ["127.0.0.1:6379:6379"]
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD:-?err}"
    volumes: ["./database:/data"]
