---
- name: Run the garbage collector
  hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Collect garbage
      ansible.builtin.shell: systemctl start --wait nix-clean-result.service && nix-collect-garbage -d
      changed_when: false
