---
- hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Copy Nix files /etc/nixos/
      synchronize:
        dest: /etc/nixos/nix
        rsync_opts:
          - --exclude="*"
          - --include=nixos
          - --include="flake.lock"
          - --include="flake.nix"
          - --include=devshell
        src: ../
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove old secrets
      synchronize:
        delete: true
        dest: ../secrets/decrypted
        perms: false
        rsync_opts: [--ignore-existing]
        src: ../secrets/secrets/
    - name: Decrypt secrets
      copy:
        dest: ../secrets/decrypted/
        directory_mode: "700"
        mode: "700"
        src: ../secrets/secrets/
- hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Copy buildtime secrets
      synchronize:
        dest: /etc/nixos/nixos/secrets/secrets.json
        rsync_opts: ["--mkpath --chown=root:root --chmod=D0700,F0600"]
        src: ../secrets/decrypted/buildtime.json
    - name: Copy runtime secrets
      synchronize:
        delete: true
        dest: /var/garuda/secrets/
        rsync_opts:
          - --chmod=D0700,F0600
          - --chown=root:root
          - --exclude=garuda/buildtime.json
        src: ../secrets/decrypted/
