---
- name: Deploy NixOS configurations
  hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Deploy Nix files
      ansible.posix.synchronize:
        dest: /etc/nixos/
        archive: true
        src: ../{{ item }}
      loop: # Filtering was for whatever reason not working properly
        - nixos # No alphabetical order to be able to push this first
        - flake.nix
        - flake.lock
        - devshell
        - docker-compose
        - home-manager
- name: Decrypt secrets locally
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove old secrets
      ansible.posix.synchronize:
        delete: true
        dest: ../secrets/decrypted
        perms: false
        rsync_opts: [--ignore-existing]
        src: ../secrets/secrets/
    - name: Decrypt secrets
      ansible.builtin.copy:
        dest: ../secrets/decrypted/
        directory_mode: "700"
        mode: "700"
        src: ../secrets/secrets/
- name: Deploy secrets
  hosts: nix
  become: true
  gather_facts: false
  tasks:
    - name: Copy buildtime secrets
      ansible.posix.synchronize:
        dest: /etc/nixos/nixos/secrets/secrets.json
        rsync_opts: ["--mkpath --chown=root:root --chmod=D0700,F0600"]
        src: ../secrets/decrypted/buildtime.json
    - name: Copy runtime secrets
      ansible.posix.synchronize:
        delete: true
        dest: /var/garuda/secrets/
        rsync_opts:
          - --chmod=D0700,F0600
          - --chown=root:root
          - --exclude=garuda/buildtime.json
        src: ../secrets/decrypted/
